--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.TRG_DICT_PUSH_TEMPLATE_IU contextFilter:PH endDelimiter:/ runOnChange:true

create or replace TRIGGER INT_COMMUNICATION.TRG_DICT_PUSH_TEMPLATE_IU
 after INSERT ON INT_COMMUNICATION.DICT_PUSH_TEMPLATE
BEGIN
   	MERGE INTO INT_COMMUNICATION.DICT_PUSH_TEMPLATE DPTT
	USING INT_COMMUNICATION.DICT_PUSH_GMA_TEMPLATE DPGT
    ON (DPTT.TPL_ID = DPGT.TPL_ID AND DPTT.TPL_LANGUAGE = DPGT.TPL_LANGUAGE)
    WHEN MATCHED THEN
    UPDATE SET LOGICAL_APPLICATION = DPGT.LOGICAL_APPLICATION;
END;
/