--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.DICT_PUSH_GMA_TEMPLATE contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE
    exc_already_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN
EXECUTE IMMEDIATE q'{
  CREATE TABLE "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" 
   (	"TPL_ID" NUMBER NOT NULL ENABLE, 
	"TPL_LANGUAGE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"LOGICAL_APPLICATION" VARCHAR2(50 CHAR), 
	"CREATED_DTTM" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATED_DTTM" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"BY_USER" VARCHAR2(128 CHAR) DEFAULT USER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INT_DATA" 
}';
EXCEPTION
    WHEN exc_already_exists THEN
        NULL;
END;
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO HCI_RO_INT_COMMUNICATION
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCI_APP_SELECT"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_INT_COMMUNICATION_RO"
/
GRANT DELETE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_INT_COMM_DICT_RW"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_INT_COMM_DICT_RW"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_INT_COMM_DICT_RW"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_INT_COMM_DICT_RW"
/
GRANT DELETE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "OFS_USER"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "OFS_USER"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "OFS_USER"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "OFS_USER"
/
GRANT DELETE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "MA_TEMP"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "MA_TEMP"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "MA_TEMP"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCPH_INT_COMM_RO"
/
GRANT DELETE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCPH_INT_COMM_DICT_RW"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCPH_INT_COMM_DICT_RW"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCPH_INT_COMM_DICT_RW"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCPH_INT_COMM_DICT_RW"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "GB_INT_COMM_RO"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "INT_ETL"
/
GRANT DELETE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_ETL"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_ETL"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_ETL"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "SAS_ETL"
/
GRANT DELETE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "ETL_USER"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "ETL_USER"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "ETL_USER"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "ETL_USER"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCI_APP_UPDATE"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "HCI_APP_INSERT"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "APPSUPPORT"
/
GRANT UPDATE ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "APPSUPPORT"
/
GRANT INSERT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "APPSUPPORT"
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_PUSH_GMA_TEMPLATE" TO "MA_TEMP"
/